# These are supported funding model platforms

github: prithwirajbose
patreon: sribasu
open_collective: prithwiraj-bose
liberapay: sribasu
custom: ["https://www.buymeacoffee.com/sribasu", buymeacoffee.com]
